Algoritmo "Imprime_For_10a1"
// Disciplina   : Lógica de Programação
// Professor   : Marcos Monteiro
// Descrição   : Exemplo utilizando a Estrutura Para decrescente
// Autor(a)    : Edelson Barboza
// Data atual  : 31/10/2022
Var

j: inteiro

Inicio
   escreval("Imprimindo de 10 a 1:")
   escreval()
   para j de 10 ate 1 passo j-1 faca
      escreval(j)
   fimpara
   escreval()
   escreval("Fogo!!!")
Fimalgoritmo