Algoritmo "Imprime_Repita_Até_1a10"
// Disciplina   : Lógica de Programação
// Professor   : Marcos Monteiro 
// Descrição   : Exemplo utilizando a Estrutura de Repetição "Repita Ate"
// Autor(a)    : Edelson Barboza
// Data atual  : 31/10/2022
Var
// Seção de Declarações das variáveis 
j: inteiro

Inicio
   escreval("Imprimindo de 1 a 10 'repita ate':")
   escreval()
   j <- 1
   repita
     escreval(j)
     j <- j+1
   ate j > 10
   escreval()
   escreval("Valor do J:",j)

Fimalgoritmo