Algoritmo "Imprime_Enquanto_1a10"
// Disciplina   : Lógica de Programação
// Professor   : Marcos Monteiro 
// Descrição   : Exemplo utilizando a Estrutura de Repetição Enquanto
// Autor(a)    : Edelson Barboza
// Data atual  : 31/10/2022
Var
// Seção de Declarações das variáveis 
j:inteiro

Inicio
   escreval("Imprimindo de 1 a 10 com 'enquanto':")
   escreval()
   j <- 1
   enquanto j < 11 faca
      escreval(j)
      j <- j+1
   fimenquanto

Fimalgoritmo