Algoritmo "Notas_Aluno"
// Disciplina   : Lógica de Programação
// Professor   : Marcos Monteiro 
// Descrição   : Cálcula a média entre duas notas informadas
// Autor(a)    : Edelson Barboza
// Data atual  : 27/10/2022
Var
// Seção de Declarações das variáveis 
nota1, nota2: real;

Inicio
   escreva("Digite a 1ª nota: ")
   leia(nota1)
   escreva("Digite a 2ª nota: ")
   leia(nota2)
   escreval()
   escreval("Média obtida: ", ((nota1 + nota2)/2))
Fimalgoritmo