Algoritmo "Exercício_Mútiplos_de_2"
// Disciplina   : Lógica de Programação
// Professor   : Marcos Monteiro 
// Descrição   : Programa que exibe os mútiplos de 2 entre 0 e 100
// Autor(a)    : Edelson Barboza
// Data atual  : 31/10/2022
Var
// Seção de Declarações das variáveis 
j:inteiro

Inicio
   escreval("Múltiplos de 2 entre 0 e 100:")
   escreval()
   para j de 0 ate 100 faca
      se (j%2=0) entao
         escreval(j)
      fimse
   fimpara

Fimalgoritmo